### DBND CI CD
### GENERAL CI CONFIG

### KNOWN ISSUES:
# `needs` doesn't work for failed job, the job after will run when the "needed" job is skipped
# A (fails) -> B (skip) -> C (runs!!!)

#image:

stages:
  - test
  - build-base
  - publish
  - staging
  - test-windows
  - ci-utils

variables:
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

  PYPI_PUBLIC_URL: https://pypi.databand.ai/simple/

### TESTS BASIC
.template__except_defaults:
  except: &except_on_skip_message
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

.template__on_every_commit:
  only: &on_every_commit
    - /^feature|fix/
    - master
    - merge_requests
    - develop
    - tags

.template__on_significant_branch:
  only: &on_significant_branch
    - master
    - merge_requests
    - develop
    - tags

### TEST TEMPLATES
.template__basic_job: &template__basic_checks_job
  stage: test
  only: *on_every_commit

.template__test_python: &template__python_test_job
  stage: test
  before_script:
    - pip install tox
    - apt-get update -y -qq
    - apt-get install -y -qq graphviz bzip2
    - export VIRTUALENV_NO_DOWNLOAD=yes
  only: *on_significant_branch
  except: *except_on_skip_message

.template__test_windows: &template__windows_tests_job
  stage: test-windows
  only: *on_significant_branch
  except: *except_on_skip_message
  needs: ["empty_job"]
  before_script:
    - echo "start"
    - whoami
  tags:
    - windows
  # TODO: new models - sqlalchemy_utils.UUID - not wokring on windows?
  when: manual


empty_job:
  # workaround for gitlab not supporting empty `needs`
  # we want build jobs starting to run right away
  stage: test
  only: *on_significant_branch
  script:
    - echo "Hello World"

pre_commit:
  <<: *template__python_test_job
  image: python:3.6
  script:
#    - tox -e pre-commit,lint,docs,readme
    - tox -e pre-commit,lint

manifest:
  <<: *template__python_test_job
  image: python:3.6
  script:
    - make test-manifest

dbnd_py27:
  <<: *template__python_test_job
  image: python:2.7
  script:
    - cd modules/dbnd
    - tox -e py27
  artifacts:
    reports:
      junit: modules/dbnd/build/junit-py27.xml

dbnd_py36:
  <<: *template__python_test_job
  image: python:3.6
  script:
    - cd modules/dbnd
    - tox -e py36
  artifacts:
    reports:
      junit: build/junit-py36.xml

dbnd_py36_windows:
  <<: *template__windows_tests_job
  script:
    - xcopy /y "modules\setup.cfg" "modules\dbnd\"
    - tox -c modules/dbnd/tox.ini -r -e win-py36

dbnd_py37:
  <<: *template__python_test_job
  image: python:3.7
  script:
    - cd modules/dbnd
    - tox -e py37
  artifacts:
    reports:
      junit: modules/dbnd/build/junit-py37.xml

dbnd_airflow_py27:
  <<: *template__python_test_job
  image: python:2.7
  script:
    - cd modules/dbnd-airflow
    - tox -e py27
  artifacts:
    reports:
      junit: modules/dbnd-airflow/build/junit-py27.xml

dbnd_airflow_py36_win:
  <<: *template__windows_tests_job
  script:
    - xcopy /y "modules\setup.cfg" "modules\dbnd-airflow\"
    - tox -c modules/dbnd-airflow/tox.ini -r -e win-py36

dbnd_airflow_py37:
  <<: *template__python_test_job
  image: python:3.7
  script:
    - cd modules/dbnd-airflow
    - tox -e py37
  artifacts:
    reports:
      junit: modules/dbnd-airflow/build/junit-py37.xml

dbnd_examples_py27:
  <<: *template__python_test_job
  image: python:2.7
  script:
    - cd examples
    - tox -e py27
  artifacts:
    reports:
      junit: .tox/dbnd_examples/junit/junit-py27.xml

dbnd_examples_py36:
  <<: *template__python_test_job
  image: python:3.6
  script:
    - cd examples
    - tox -e py36
  artifacts:
    reports:
      junit: .tox/dbnd_examples/junit/junit-py36.xml

build_pypi_whl:
  stage: build-base
  image: python:3.6
  needs: ["empty_job"]
  script:
    - python setup.py sdist bdist_wheel
    - make dist-modules
    - ls dist/databand-*.whl | xargs -n 1 basename > dbnd-wheel-name
  artifacts:
    paths:
      - dist/*
      - dbnd-wheel-name
  only: *on_significant_branch

#downstream:
#  stage: staging
#  trigger:
#    project: databand/databand
#    branch: develop
#  only: *on_significant_branch

publish_dbnd_package:
  stage: publish
  image: python:3.6-slim-buster
  variables:
    GIT_STRATEGY: none
  needs:
    - build_pypi_whl
  before_script:
    - pip install twine
  script:
    - twine upload --repository-url ${PYPI_PUBLIC_URL} dist/*
  only:
    - tags
  when: manual
