exclude: >
  (?x)^(
      .+/airflow_override/.+|
      .+/_vendor/.+|
      .+/reliable_http_client.py
  )$
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        exclude: dbnd/_vendor
        types: []

#  - repo: https://github.com/asottile/seed-isort-config
#    rev: v1.0.1
#    hooks:
#      - id: seed-isort-config
#        language_version: python3.6

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
        exclude: dbnd/_vendor
